//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.JHDBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JHDBService.IJHDBService")]
    public interface IJHDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/GetDataSet", ReplyAction="http://tempuri.org/IJHDBService/GetDataSetResponse")]
        System.Data.DataSet GetDataSet(string strSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/Commands", ReplyAction="http://tempuri.org/IJHDBService/CommandsResponse")]
        string Commands(string CommandsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/CommandGeneric", ReplyAction="http://tempuri.org/IJHDBService/CommandGenericResponse")]
        byte[] CommandGeneric(byte[] commands);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/SetConnectString", ReplyAction="http://tempuri.org/IJHDBService/SetConnectStringResponse")]
        void SetConnectString(string ClientConnectType, string _connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/GetDBServiceConnectType", ReplyAction="http://tempuri.org/IJHDBService/GetDBServiceConnectTypeResponse")]
        string GetDBServiceConnectType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/AddIP", ReplyAction="http://tempuri.org/IJHDBService/AddIPResponse")]
        void AddIP(string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/GetUserNameAndPassword", ReplyAction="http://tempuri.org/IJHDBService/GetUserNameAndPasswordResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UserName")]
        string GetUserNameAndPassword(out string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/GetServerIPAddress", ReplyAction="http://tempuri.org/IJHDBService/GetServerIPAddressResponse")]
        string GetServerIPAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/RemoveIP", ReplyAction="http://tempuri.org/IJHDBService/RemoveIPResponse")]
        void RemoveIP(string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/SetUserNameAndPassword", ReplyAction="http://tempuri.org/IJHDBService/SetUserNameAndPasswordResponse")]
        void SetUserNameAndPassword(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/Register", ReplyAction="http://tempuri.org/IJHDBService/RegisterResponse")]
        void Register(string SystemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/Test", ReplyAction="http://tempuri.org/IJHDBService/TestResponse")]
        void Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHDBService/ServerNow", ReplyAction="http://tempuri.org/IJHDBService/ServerNowResponse")]
        string ServerNow();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJHDBServiceChannel : EMR.JHDBService.IJHDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JHDBServiceClient : System.ServiceModel.ClientBase<EMR.JHDBService.IJHDBService>, EMR.JHDBService.IJHDBService {
        
        public JHDBServiceClient() {
        }
        
        public JHDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JHDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataSet(string strSQL) {
            return base.Channel.GetDataSet(strSQL);
        }
        
        public string Commands(string CommandsXML) {
            return base.Channel.Commands(CommandsXML);
        }
        
        public byte[] CommandGeneric(byte[] commands) {
            return base.Channel.CommandGeneric(commands);
        }
        
        public void SetConnectString(string ClientConnectType, string _connectionString) {
            base.Channel.SetConnectString(ClientConnectType, _connectionString);
        }
        
        public string GetDBServiceConnectType() {
            return base.Channel.GetDBServiceConnectType();
        }
        
        public void AddIP(string IP) {
            base.Channel.AddIP(IP);
        }
        
        public string GetUserNameAndPassword(out string Password) {
            return base.Channel.GetUserNameAndPassword(out Password);
        }
        
        public string GetServerIPAddress() {
            return base.Channel.GetServerIPAddress();
        }
        
        public void RemoveIP(string IP) {
            base.Channel.RemoveIP(IP);
        }
        
        public void SetUserNameAndPassword(string UserName, string Password) {
            base.Channel.SetUserNameAndPassword(UserName, Password);
        }
        
        public void Register(string SystemName) {
            base.Channel.Register(SystemName);
        }
        
        public void Test() {
            base.Channel.Test();
        }
        
        public string ServerNow() {
            return base.Channel.ServerNow();
        }
    }
}
