//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHEMR.JHEMRAutoUpdate.JHAutoUpdateClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JHAutoUpdateClient.IJHAutoUpdateService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IJHAutoUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHAutoUpdateService/get_All_UploadFile", ReplyAction="http://tempuri.org/IJHAutoUpdateService/get_All_UploadFileResponse")]
        System.Data.DataSet get_All_UploadFile(out int imax_No, string strDown_NO_From);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHAutoUpdateService/getList", ReplyAction="http://tempuri.org/IJHAutoUpdateService/getListResponse")]
        System.Data.DataSet getList(out int imax_No, string strDown_NO_From);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJHAutoUpdateService/getStr", ReplyAction="http://tempuri.org/IJHAutoUpdateService/getStrResponse")]
        string getStr(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJHAutoUpdateServiceChannel : JHEMR.JHEMRAutoUpdate.JHAutoUpdateClient.IJHAutoUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JHAutoUpdateServiceClient : System.ServiceModel.ClientBase<JHEMR.JHEMRAutoUpdate.JHAutoUpdateClient.IJHAutoUpdateService>, JHEMR.JHEMRAutoUpdate.JHAutoUpdateClient.IJHAutoUpdateService {
        
        public JHAutoUpdateServiceClient() {
        }
        
        public JHAutoUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JHAutoUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHAutoUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHAutoUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet get_All_UploadFile(out int imax_No, string strDown_NO_From) {
            return base.Channel.get_All_UploadFile(out imax_No, strDown_NO_From);
        }
        
        public System.Data.DataSet getList(out int imax_No, string strDown_NO_From) {
            return base.Channel.getList(out imax_No, strDown_NO_From);
        }
        
        public string getStr(string str) {
            return base.Channel.getStr(str);
        }
    }
}
